import type { ThemeNote } from 'vuepress-theme-plume'
import { defineNoteConfig } from 'vuepress-theme-plume'

export const Guide: ThemeNote = defineNoteConfig({
    dir: 'guide',
    link: '/guide/',
    sidebar: [
        {
            text: '基本信息',
            collapsed: false,
            icon: 'carbon:idea',
            prefix: 'basicinfo',
            items: [
                'intro',
                'framework',
            ],
        },
        {
            text: '从这里开始',
            collapsed: false,
            icon: 'carbon:idea',
            prefix: 'quickstart',
            items: [
                'install',
                'quickstart',
                'translation',
                'sft_synthesis',
                'conversation_synthesis',
                "reasoning_general",
                "prompted_vqa",
                "mathquestion_extract",
                'knowledge_cleaning',
                'quick_general_text_evaluation',
                'speech_transcription',
            ],
        },
        //         {
        //     text: 'Dataflow 智能体',
        //     collapsed: false,
        //     icon: 'ri:robot-2-line',
        //     prefix: 'agent',
        //     items: [
        //         "DataFlow-AgentPipelineOrchestration",
        //     ],
        // },
        {
            text:"流水线教程",
            collapsed: false,
            icon: 'carbon:flow',
            prefix: 'pipelines',
            items: [
                "TextPipeline",
                "ReasoningPipeline",
                "Text2SqlPipeline",
                "Doc2QAPipeline",
                "AgenticRAGPipeline",
                "RAREPipeline",
                "KnowledgeBaseCleaningPipeline",
                "FuncCallPipeline",
            ]
        },
        {
            text: "通用算子",
            collapsed: false,
            icon: 'material-symbols:analytics-outline',
            prefix: 'general_operators',
            items: [
                "text_evaluation_operators",
                "text_process_operators",
                "text_generate_operators",
            ]
        },
        {
            text: "专用算子",
            collapsed: false,
            icon: 'material-symbols:analytics-outline',
            prefix: 'domain_specific_operators',
            items: [
                "reasoning_operators",
                "text2sql_operators",
                "rare_operators",
                "knowledgebase_QA_operators",
                "agenticrag_operators",
                "funccall_operators"
                // "video_process",
            ]
        },
        {
            text: "Agent for Dataflow",
            collapsed: false,
            icon: 'mdi:face-agent',
            prefix: 'agent',
            items: [
                "agent_for_data",
                "DataFlow-AgentPipelineOrchestration",
                "agent_for_dataflow_new",
            ]
        },
        // {
        //     text: '写作',
        //     icon: 'fluent-mdl2:edit-create',
        //     collapsed: false,
        //     items: [
        //         {
        //             text: 'markdown',
        //             icon: 'material-symbols:markdown-outline',
        //             prefix: 'markdown',
        //             collapsed: true,
        //             items: [
        //                 'basic',
        //                 'extensions',
        //                 'icons',
        //                 'mark',
        //                 'plot',
        //                 'abbr',
        //                 'annotation',
        //                 'card',
        //                 'steps',
        //                 'file-tree',
        //                 'code-tree',
        //                 'field',
        //                 'tabs',
        //                 'timeline',
        //                 'demo-wrapper',
        //                 'flex',
        //                 'collapse',
        //                 'npm-to',
        //                 'caniuse',
        //                 'chat',
        //                 'include',
        //             ],
        //         },
        //         {
        //             text: '代码块',
        //             prefix: 'code',
        //             icon: 'ph:code-bold',
        //             collapsed: true,
        //             items: [
        //                 'intro',
        //                 'features',
        //                 'copy-code',
        //                 'code-tabs',
        //                 'import',
        //                 'twoslash',
        //             ],
        //         },
        //         {
        //             text: '代码演示',
        //             prefix: 'repl',
        //             icon: 'carbon:demo',
        //             collapsed: true,
        //             items: [
        //                 'frontend',
        //                 'rust',
        //                 'golang',
        //                 'kotlin',
        //                 'python',
        //                 'codepen',
        //                 'jsFiddle',
        //                 'codeSandbox',
        //                 'replit',
        //                 'frontend-deprecated',
        //             ],
        //         },
        //         {
        //             text: '图表',
        //             icon: 'mdi:chart-line',
        //             prefix: 'chart',
        //             collapsed: true,
        //             items: [
        //                 'chart',
        //                 'echarts',
        //                 'mermaid',
        //                 'flowchart',
        //                 'markmap',
        //                 'plantuml',
        //             ],
        //         },
        //         {
        //             text: '资源嵌入',
        //             icon: 'dashicons:embed-video',
        //             prefix: 'embed',
        //             collapsed: true,
        //             items: [
        //                 'pdf',
        //                 'bilibili',
        //                 'youtube',
        //                 'artplayer',
        //                 'audioReader',
        //             ],
        //         },
        //     ],
        // },
        // {
        //     text: '功能',
        //     icon: 'lucide:box',
        //     collapsed: false,
        //     prefix: 'features',
        //     items: [
        //         'icon',
        //         'search',
        //         'comments',
        //         'bulletin',
        //         'encryption',
        //         'contributors',
        //         'changelog',
        //         'copyright',
        //         'watermark',
        //         'friend-links',
        //         'replace-assets',
        //         'seo',
        //         'sitemap',
        //     ],
        // },
        // {
        //     text: '组件',
        //     prefix: 'components',
        //     icon: 'uiw:component',
        //     collapsed: false,
        //     items: [
        //         'badge',
        //         'icon',
        //         'plot',
        //         'card',
        //         'link-card',
        //         'image-card',
        //         'card-grid',
        //         'card-masonry',
        //         'home-box',
        //         'repo-card',
        //         'npm-badge',
        //         'swiper',
        //     ],
        // },
        // {
        //     text: '自定义',
        //     icon: 'material-symbols:dashboard-customize-outline-rounded',
        //     collapsed: false,
        //     prefix: 'custom',
        //     items: [
        //         'home',
        //         'style',
        //         'slots',
        //         'component-overrides',
        //     ],
        // },
        // {
        //     text: 'API',
        //     icon: 'mdi:api',
        //     prefix: 'api',
        //     collapsed: false,
        //     items: [
        //         'client',
        //         'node',
        //     ],
        // },
    ],
})
